language: csharp
solution: Wavefront.AppMetrics.SDK.CSharp.sln
mono: none
dotnet: 2.1.300

install:
 - dotnet restore

script:
 - dotnet build
 - dotnet test test/Wavefront.AppMetrics.SDK.CSharp.Test/Wavefront.AppMetrics.SDK.CSharp.Test.csproj
